### ISSUE TITLE
在context切换过程中似乎存在栈溢出的问题

### ISSUE THREAD

**Issue by gdl1245105585** [NJU-ProjectN/rt-thread-am#2]
在使用native运行rtt中，如果使用kcontext函数建立任务栈并execute生成的线程，因为其建立的栈中的RSP指针指向了栈顶，会导致运行中产生的数据被依次压栈到栈顶的位置，也即保存Context的位置。如果当线程运行中有更高优先级的线程打断了该线程，则该线程会将context保存在栈顶的位置，也即局部变量保存的位置，从而破坏了线程中的运行安全。

**Comment by gdl1245105585** [comment]
![1709795556828](https://github.com/NJU-ProjectN/rt-thread-am/assets/74965039/beb7d8ff-5803-4e5d-8bb3-740301c3bf4a)

**Comment by gdl1245105585** [comment]
![image](https://github.com/NJU-ProjectN/rt-thread-am/assets/74965039/19cbf451-266f-4d53-826f-0f170ae8fc8b)

**Comment by sashimi-yzh** [comment]
我还没理解你的问题, 栈往低地址生长, 所以不会覆盖context, 所以你描述的情况感觉没问题?

**Comment by gdl1245105585** [comment]
![Uploading 实例.jpg…]()
通过这个图可能会显示的更直观一些   栈指针指向的是栈顶的位置
而不是第一个未被使用的内存

**Comment by gdl1245105585** [comment]
![Uploading 图片.png…]()

通过这个图可能会显示的更直观一些 栈指针指向的是栈顶的位置
而不是第一个未被使用的内存

**Comment by gdl1245105585** [comment]
![Uploading 实例.jpg…]()

**Comment by gdl1245105585** [comment]
抱歉，上次上传的图是我修改代码后产生的图片，我重新上传
![图片](https://github.com/NJU-ProjectN/rt-thread-am/assets/74965039/3882aa28-9985-4c48-845d-79033b7ec3df)

**Comment by sashimi-yzh** [comment]
我还没看出问题, 你是不是觉得saved RSP会导致后续的压栈操作会把context覆盖掉? 如果你是这么想, 可以尝试再梳理一下异常处理的全过程. 如果你觉得是其他问题, 可以尝试描述得更详细一些.

**Comment by gdl1245105585** [comment]
压栈操作把context覆盖掉不会产生问题，因为context只对当前切换生效。但当再次需要保存context时，其保存的地址仍然为栈顶，将压栈的数据覆盖掉，这会产生栈上数据的丢失

**Comment by sashimi-yzh** [comment]
```
但当再次需要保存context时，其保存的地址仍然为栈顶
```
保存的地址为栈顶, 不就正好说明数值上比rsp小的内存位置都是可用的吗? 这样就不会覆盖栈上的已有数据, 除非是栈溢出了.

**Comment by gdl1245105585** [comment]
数值上比rsp小的内存地址时可用的   实际上比rsp小的地址中已经存储栈中数据   我可以通过这个图展示相关数值
![图片](https://github.com/NJU-ProjectN/rt-thread-am/assets/74965039/4eb1b486-c609-487f-a57c-7ab7094c3461)
其中0x55961eba79d0 到0x55961eba7840已经存储了栈上数据，而切换中存储的context空间为0x55961eba79d0  - 0x55961eba7578 ，这其中就产生了数据丢失

**Comment by sashimi-yzh** [comment]
```
而切换中存储的context空间为0x55961eba79d0 - 0x55961eba7578
```
我对这个表述存疑, `context save to:0x55961eba7578`这句话是在哪里输出的? 输出的是哪个变量的值?

**Comment by gdl1245105585** [comment]
> context save to:0x55961eba7578这句话是在哪里输出的?
这句话输出来自于对“”void rt_hw_context_switch(rt_ubase_t from, rt_ubase_t to)“” 中from 的一级解引用
![图片](https://github.com/NJU-ProjectN/rt-thread-am/assets/74965039/9cb2ed78-563f-44d2-8097-dcf0ac26072b)

**Comment by gdl1245105585** [comment]
`context save to:0x55961eba7578` 出自
![图片](https://github.com/NJU-ProjectN/rt-thread-am/assets/74965039/8480f0d9-30ec-48fd-accc-c2d687d22dd4)
`when switch rsp point to` 出自event_handle中 `printf("when switch rsp point to :%p   ",c->uc.uc_mcontext.gregs[REG_RSP]);`

**Comment by sashimi-yzh** [comment]
我已经不太能捋清楚你这些printf的情况了, 只能从理论上针对你的情况做一些推论.

AM CTE的代码只会把context保存在比rsp数值小的位置, 而在没有发生栈溢出的情况下, “比rsp数值小的内存位置没有有效数据”这个表述是合理的, 因为栈是往下生长的. 既然你发现比rsp数值小的位置存在有效数据, 那就应该检查这些有效数据是什么时候被谁写入的.

如果你想进一步讨论上面的案例, 可能需要你再详细捋一下问题发生的前因后果: 什么时候谁在栈上的哪个位置写入了什么数据, 哪一段栈空间本来应该属于谁的, 究竟是谁在什么时候往不该写入的地方写入了什么数据.

**Comment by gdl1245105585** [comment]
我知道我和您的误区在哪里了，您在强调AM  CTE保证context保存在比rsp小的区域 ，我也认同这一点。
但是， RTT程序并不保证这一点    ，RTT会要求我们将context保存在某个特定的地址，很不幸的是，这个特定的地址比rsp要大，这个过程发生了栈溢出。关于为什么这个特定的地址比rsp的要大，是因为rtt将一直将新的context保存到第一次context存储的区域。更多详细的内容我会在明早详细的阐述

在2024-03-07 ***@***.***写道：

我已经不太能捋清楚你这些printf的情况了, 只能从理论上针对你的情况做一些推论.

AM CTE的代码只会把context保存在比rsp数值小的位置, 而在没有发生栈溢出的情况下, “比rsp数值小的内存位置没有有效数据”这个表述是合理的, 因为栈是往下生长的. 既然你发现比rsp数值小的位置存在有效数据, 那就应该检查这些有效数据是什么时候被谁写入的.

如果你想进一步讨论上面的案例, 可能需要你再详细捋一下问题发生的前因后果: 什么时候谁在栈上的哪个位置写入了什么数据, 哪一段栈空间本来应该属于谁的, 究竟是谁在什么时候往不该写入的地方写入了什么数据.

**Comment by sashimi-yzh** [comment]
```
关于为什么这个特定的地址比rsp的要大，是因为rtt将一直将新的context保存到第一次context存储的区域
```
这个感觉是你实现的问题, 我的实现没有这个问题.

**Comment by gdl1245105585** [comment]
我可以百分百确定，你的实现存在问题，这个特定的地址是保存在thread->sp中，而在线程切换的过程中，你没有机会接触这个变量，因为这在函数中是值传递而不是地址传递，所以我可以确定并不是我实现的问题

在2024-03-08 ***@***.***写道：

关于为什么这个特定的地址比rsp的要大，是因为rtt将一直将新的context保存到第一次context存储的区域


这个感觉是你实现的问题, 我的实现没有这个问题.

**Comment by gdl1245105585** [comment]
thread->sp   是指向上下文结构体的指针，如果你不修改这一变量值，那你就只能在该变量指向的地方存放结构体。而且线程切换相关函数中，确实有办法保证栈不溢出，但实现方法相当丑陋。在event_handle中，首先读取当前栈指针，随后建立新的context，然后将Thread->sp指向context。其中为了保证实现的规范，需要遵守一些额外的约定，不能实现指令集层面的迁移。我不认为你采用了这种方法。

在2024-03-08 ***@***.***写道：

关于为什么这个特定的地址比rsp的要大，是因为rtt将一直将新的context保存到第一次context存储的区域


这个感觉是你实现的问题, 我的实现没有这个问题.

**Comment by sashimi-yzh** [comment]
```
我可以百分百确定，你的实现存在问题，这个特定的地址是保存在thread->sp中，而在线程切换的过程中，你没有机会接触这个变量，因为这在函数中是值传递而不是地址传递，所以我可以确定并不是我实现的问题
```
先明确一下, `thread->sp`的地址通过`rt_hw_context_switch()`的`from`参数传进来. 如果对前面这句话的理解一致, 我确实在CTE的过程中访问到它了, 具体怎么实现, 在PA讲义里面有提示, 没有你想象中那么丑陋, 都是arch-independent的纯C代码.

**Comment by sashimi-yzh** [comment]
话说, 你怀疑我的代码有问题, 是在什么情况下有问题? 是一旦发生线程切换就会出现问题, 还是在某些极端条件下才会出问题?

**Comment by gdl1245105585** [comment]
>话说, 你怀疑我的代码有问题, 是在什么情况下有问题? 是一旦发生线程切换就会出现问题, 还是在某些极端条件下才会出问题?

在现在的RTT测试覆盖不到当一个线程切出后再次切入，所以我怀疑在这里会出现问题

我可能明白你的意思了，那你的实现代码可能并不会导致出现问题。

但是，你是否认为context在栈上所占据的空间是不需要被保护的，并且当context save以后一定立刻会有另一个context被restore，所以无论线程切换前后，你的rsp指针始终都会指向context 的顶部并准备覆写相关区域？

**Comment by sashimi-yzh** [comment]
一个变量是否需要被保护, 取决于这个变量是否会被其他线程共享, 后者是变量的一种属性. 你可以尝试整理一下不同类型变量的作用域, 生存期和共享情况, 这能指导你理解问题并寻找合适的解决方案. 事实上, PA中相关的分析过程就是在引导大家进行这样的整理, PA中的巧妙解决方案本质上就是把这些属性利用好.

至于rsp, 因为它是arch-dependent的, 我们不应该直接在RT-Thread中直接访问rsp, 因此它的性质仅仅由AM的CTE来保证.

**Comment by gdl1245105585** [comment]
我想向您说明的是，您在AM CTE中对context的保存是非常不恰当的，在其中您将context置于栈的保护之外，确实可以增加可用的栈空间，但其中的代价是需要有非常强的保证context在被保存后到下次被恢复之前不会有任何的数据被写入到栈中。

但在事实上，我们还有一些不同于RTT的ISP过程，会需要我们先保存当前上下文，而后再检查诸如中断等，从而获取下一线程并执行。这一过程中是会有可能因为您对context不妥当的处理，导致栈溢出的风险。

至于RSP，只是用来向您说明，程序确实是如同我认为的方式运行

**Comment by sashimi-yzh** [comment]
```
您在AM CTE中对context的保存是非常不恰当的，在其中您将context置于栈的保护之外
```
你是怎么得出这个结论的?

**Comment by gdl1245105585** [comment]
抱歉，前两天在发烧，没有来得及回复您

>你是怎么得出这个结论的?

您是在'ev_handler'这一个函数中完成的对context的保存工作，因为您采用了arch-independent的纯C代码，那么在‘ev_handler‘完成之后，其使用的栈空间都会被释放，在其中申请的context的空间将不再被保护

如果线程立刻被切换，这不会导致任何问题，因为您在下次切换回来之前，对应'ev_handler中使用的空间'实际上不可能被使用，也就避免了栈溢出的问题

但是很不幸的是，如果线程没有被切换，仅仅只是将当前线程挂起，并等待中断信号的到来？

如果没有切换，rsp指针指向的位置一定是context上方的某一个位置，当一个time irq到来以后，'sig_handler'会调用'setup_stack'，这会有把context空间部分覆盖掉的隐患，这是我希望给您强调的。

可能这个bug不会触发在RTT中，因为RTT有着对切换有着强制性的要求，但不是每一个RTOS都会有着同样的要求。

当然，如果我的理解有着问题，您有**采用纯C代码的情况下，仍然能保证context空间被保护的方法，我为我的水平欠佳和耽误您的时间向您致歉“”

**Comment by gdl1245105585** [comment]
抱歉，前两天在发烧，没有来得及回复您

>你是怎么得出这个结论的?

您是在'ev_handler'这一个函数中完成的对context的保存工作，因为您采用了arch-independent的纯C代码，那么在‘ev_handler‘完成之后，其使用的栈空间都会被释放，在其中申请的context的空间将不再被保护

如果线程立刻被切换，这不会导致任何问题，因为您在下次切换回来之前，对应'ev_handler中使用的空间'实际上不可能被使用，也就避免了栈溢出的问题

但是很不幸的是，如果线程没有被切换，仅仅只是将当前线程挂起，并等待中断信号的到来？

如果没有切换，rsp指针指向的位置一定是context上方的某一个位置，当一个time irq到来以后，'sig_handler'会调用'setup_stack'，这会有把context空间部分覆盖掉的隐患，这是我希望给您强调的。

可能这个bug不会触发在RTT中，因为RTT有着对切换有着强制性的要求，但不是每一个RTOS都会有着同样的要求。

当然，如果我的理解有着问题，您有**采用纯C代码的情况下，仍然能保证context空间被保护的方法，我为我的水平欠佳和耽误您的时间向您致歉“”

**Comment by gdl1245105585** [comment]
抱歉，前两天在发烧，没有来得及回复您

>你是怎么得出这个结论的?

您是在`ev_handler`这一个函数中完成的对context的保存工作，因为您采用了arch-independent的纯C代码，那么在`ev_handler`完成之后，其使用的栈空间都会被释放，在其中申请的context的空间将不再被保护

如果线程立刻被切换，这不会导致任何问题，因为您在下次切换回来之前，对应`ev_handler`中使用的空间'实际上不可能被使用，也就避免了栈溢出的问题

但是很不幸的是，如果线程没有被切换，仅仅只是将当前线程挂起，并等待中断信号的到来？

如果没有切换，rsp指针指向的位置一定是context上方的某一个位置，当一个time irq到来以后，`sig_handler`会调用`setup_stack`，这会有把context空间部分覆盖掉的隐患，这是我希望给您强调的。

可能这个bug不会触发在RTT中，因为RTT有着对切换有着强制性的要求，但不是每一个RTOS都会有着同样的要求。

当然，如果我的理解有着问题，您有**采用纯C代码的情况下，仍然能保证context空间被保护的方法，我为我的水平欠佳和耽误您的时间向您致歉**

**Comment by sashimi-yzh** [comment]
> 您是在ev_handler这一个函数中完成的对context的保存工作

不是, context的保存工作一直都是AM CTE来完成的, 不管是`native`还是`riscv-nemu`, 这就是AM CTE约定的行为. 因此, 你接下来的分析和结论都跟我的情况不符.

你之前应该完成过PA3, 但看起来你的理解并不是基于AM的行为, 下的很多结论都在我意料之外(当然也不符合我的情况), 所以我确实不是很能明白你为什么会这么想.

**Comment by gdl1245105585** [comment]
那我明白了，我们用的完全不是一个方法。我是将ev_handler理解成了类似syscall的操作，用以操作这一权限下不允许我操作的代码，因此在其中我自行保存了context数据并切换了当前线程的指向。很痛苦的是，在我修改完对应的代码以后，包含RTT在内的RTOS都是可以正常运行的，所以我一度认为我是正确的。非常抱歉我理解出现了问题，我会结束这个issue。

**Comment by gdl1245105585** [comment]
那我明白了，我们用的完全不是一个方法。我是将`ev_handler`理解成了类似`syscall`的操作，用以操作这一权限下不允许我操作的代码，因此在其中我自行保存了context数据并切换了当前线程的指向。很痛苦的是，在我修改完对应的代码以后，包含RTT在内的RTOS都是可以正常运行的，所以我一度认为我是正确的。非常抱歉我理解出现了问题，我会结束这个issue。
