### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by rez5427** [NJU-ProjectN/rt-thread-am#4]
这个下载下来按照一生一芯的步骤编译就报了下面图片的错误。看了一天了不知道怎么解决。自己对编译器了解比较少。
似乎搜着和编译器版本相关。
![image](https://github.com/user-attachments/assets/27673ff0-cd26-4fb8-8b1d-7f2aaf2bb684)

**Comment by sashimi-yzh** [comment]
我这边复现不了这个问题
